# Generated by Django 4.0.9 on 2023-02-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Diary', 'verbose_name_plural': 'Diaries'},
        ),
    ]
