# Generated by Django 4.1.7 on 2023-03-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_diary", "0002_alter_diary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={"verbose_name": "My Diary", "verbose_name_plural": "My Diaries"},
        ),
        migrations.AlterField(
            model_name="diary",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Written at"),
        ),
        migrations.AlterField(
            model_name="diary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
